// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umsjlirrpmrtkgjovjnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtc2psaXJycG1ydGtnam92am54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTUxOTIsImV4cCI6MjA2Mjg3MTE5Mn0.ygwr76Ctco-lJuwt4HxV9bEOPVNJxyf3qNwCp4P62cE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);